### ISSUE TITLE
torrodle: command not found / I can't use torrodle because of this error

### ISSUE THREAD

**Issue by HasanAbbadi** [tnychn/torrodle#6]
whenever i type in "torrodle" in the terminal this massage appears "torrodle: command not found
"  as shown in the picture.
i did install it correctly and it didn't show an error while installing anything.

I really like this tool and hope you can fix this soon.

Thanks.
![Screenshot at 2021-02-04 16-30-25](https://user-images.githubusercontent.com/78548167/106906921-58126f80-6706-11eb-88e5-dec9a9e548c9.png)

**Comment by tnychn** [comment]
Please ensure that `$GOPATH/bin` (`$GOBIN`) is in your `$PATH`.

I'll close this issue for now as this looks more like a system environment configuration problem than an issue related to torrodle itself. Feel free to reopen the issue if the problem persists.

**Comment by HasanAbbadi** [comment]
Hey, I'm really sorry to bother you again ':0
But I just switched to Ubuntu and I am like a boomer that is still learning everything about this OS

so can u guide me on how exactly can i do that solution you provided ?

Thanks.

**Comment by tnychn** [comment]
Add the following lines to your `~/.bashrc` or `~/.zshrc`:
```shell
export GOPATH=$HOME/go 
export PATH=$GOPATH/bin:$PATH
```
https://askubuntu.com/questions/60218/how-to-add-a-directory-to-the-path
https://stackoverflow.com/questions/21001387/how-do-i-set-the-gopath-environment-variable-on-ubuntu-what-file-must-i-edit

**Comment by HasanAbbadi** [comment]
I did that, but still the same problem, here :
![Screenshot from 2021-02-06 08-26-56](https://user-images.githubusercontent.com/78548167/107111039-54413300-6855-11eb-9bc2-8aa680794dae.png)
![Screenshot from 2021-02-06 08-28-27](https://user-images.githubusercontent.com/78548167/107111040-586d5080-6855-11eb-9794-d0522d30e123.png)

did I do something wrong?
do I need to reboot or something?

Thanks.

**Comment by tnychn** [comment]
How did you install torrodle? Using the prebuilt binaries or using `go get github.com/tnychn/torrodle/cmd/...`?

If you are using a prebuilt binary, just run the binary in the command line.
```shell
chmod +x torrodle # if the file does not already have execute permission yet
./torrodle # run the binary
```

**Comment by HasanAbbadi** [comment]
alright, thank you anyways :)
